env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  no-underscore-dangle:
    - off
  jsx-a11y/no-static-element-interactions:
    - off
  jsx-a11y/click-events-have-key-events:
    - off
  max-len:
    - error
    - 130
